### ISSUE TITLE
1.2.0 release for SBT 0.13

### ISSUE THREAD

**Issue by daniel-shuy** [permutive/sbt-liquibase-plugin#3]
I noticed that the `build.sbt` for `1.2.0` still has SBT `0.13` in `crossSbtVersions`, but the release for `1.2.0` for SBT `0.13` is not found in Maven Central.

Is SBT `0.13` no longer supported or was `1.2.0` accidentally not cross published?

**Comment by travisbrown** [comment]
Hi @daniel-shuy! The omission of 0.13 was semi-accidental, I guess—we had to change our publishing config after switching the project itself to sbt 1, and I only published 1.2.0 for 1.x because I thought we'd already dropped 0.13.

I've just sent 1.2.0 artifacts for sbt 0.13 on their way to Maven Central, so they should [be available](http://central.maven.org/maven2/com/permutive/sbt-liquibase_2.10_0.13/) soon.

In the future I think we'll be happy to continue publishing for sbt 0.13 for as long as it's convenient, but if that changes we'll probably drop support rather than having version-specific code, given that sbt 1 has been out for more than two years now.

**Comment by daniel-shuy** [comment]
Thank you. I actually don't mind if support for SBT 0.13 is dropped, but I would really appreciate it if it was documented in the Release Notes, or in the `README`, eg.

| Plugin version | SBT version |
|-----------------| -------------|
| 1.1.x                | 0.13             |
| 1.2.x                | 1.x               |

**Comment by travisbrown** [comment]
Got it, thanks! If / when we do drop 0.13 support we'll flag it in both the README and the release notes.
